// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: dhclient.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DHClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device string `protobuf:"bytes,1,opt,name=Device,proto3" json:"Device,omitempty"`
}

func (x *DHClient) Reset() {
	*x = DHClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhclient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DHClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHClient) ProtoMessage() {}

func (x *DHClient) ProtoReflect() protoreflect.Message {
	mi := &file_dhclient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHClient.ProtoReflect.Descriptor instead.
func (*DHClient) Descriptor() ([]byte, []int) {
	return file_dhclient_proto_rawDescGZIP(), []int{0}
}

func (x *DHClient) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type DHClientManaged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Device string `protobuf:"bytes,2,opt,name=Device,proto3" json:"Device,omitempty"`
}

func (x *DHClientManaged) Reset() {
	*x = DHClientManaged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhclient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DHClientManaged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHClientManaged) ProtoMessage() {}

func (x *DHClientManaged) ProtoReflect() protoreflect.Message {
	mi := &file_dhclient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHClientManaged.ProtoReflect.Descriptor instead.
func (*DHClientManaged) Descriptor() ([]byte, []int) {
	return file_dhclient_proto_rawDescGZIP(), []int{1}
}

func (x *DHClientManaged) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DHClientManaged) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type DHClientManagerListArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DHClientManagerListArgs) Reset() {
	*x = DHClientManagerListArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhclient_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DHClientManagerListArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHClientManagerListArgs) ProtoMessage() {}

func (x *DHClientManagerListArgs) ProtoReflect() protoreflect.Message {
	mi := &file_dhclient_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHClientManagerListArgs.ProtoReflect.Descriptor instead.
func (*DHClientManagerListArgs) Descriptor() ([]byte, []int) {
	return file_dhclient_proto_rawDescGZIP(), []int{2}
}

type DHClientManagedId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *DHClientManagedId) Reset() {
	*x = DHClientManagedId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhclient_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DHClientManagedId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHClientManagedId) ProtoMessage() {}

func (x *DHClientManagedId) ProtoReflect() protoreflect.Message {
	mi := &file_dhclient_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHClientManagedId.ProtoReflect.Descriptor instead.
func (*DHClientManagedId) Descriptor() ([]byte, []int) {
	return file_dhclient_proto_rawDescGZIP(), []int{3}
}

func (x *DHClientManagedId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DHClientManagerListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DHClientsManaged []*DHClientManaged `protobuf:"bytes,1,rep,name=DHClientsManaged,proto3" json:"DHClientsManaged,omitempty"`
}

func (x *DHClientManagerListReply) Reset() {
	*x = DHClientManagerListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhclient_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DHClientManagerListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHClientManagerListReply) ProtoMessage() {}

func (x *DHClientManagerListReply) ProtoReflect() protoreflect.Message {
	mi := &file_dhclient_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHClientManagerListReply.ProtoReflect.Descriptor instead.
func (*DHClientManagerListReply) Descriptor() ([]byte, []int) {
	return file_dhclient_proto_rawDescGZIP(), []int{4}
}

func (x *DHClientManagerListReply) GetDHClientsManaged() []*DHClientManaged {
	if x != nil {
		return x.DHClientsManaged
	}
	return nil
}

var File_dhclient_proto protoreflect.FileDescriptor

var file_dhclient_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x68, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2e,
	0x66, 0x65, 0x6c, 0x69, 0x78, 0x2e, 0x67, 0x6f, 0x49, 0x53, 0x43, 0x44, 0x48, 0x43, 0x50, 0x22,
	0x22, 0x0a, 0x08, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x39, 0x0a, 0x0f, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x19,
	0x0a, 0x17, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x48, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x76,
	0x0a, 0x18, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5a, 0x0a, 0x10, 0x44, 0x48,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x2e, 0x66, 0x65, 0x6c, 0x69, 0x78, 0x2e, 0x67, 0x6f, 0x49, 0x53, 0x43,
	0x44, 0x48, 0x43, 0x50, 0x2e, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x64, 0x52, 0x10, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x32, 0xce, 0x03, 0x0a, 0x0f, 0x44, 0x48, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x65, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x2e, 0x66, 0x65, 0x6c, 0x69, 0x78, 0x2e, 0x67, 0x6f, 0x49, 0x53, 0x43,
	0x44, 0x48, 0x43, 0x50, 0x2e, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x30, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x66, 0x65,
	0x6c, 0x69, 0x78, 0x2e, 0x67, 0x6f, 0x49, 0x53, 0x43, 0x44, 0x48, 0x43, 0x50, 0x2e, 0x44, 0x48,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x49, 0x64, 0x22,
	0x00, 0x12, 0x79, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x70, 0x6f, 0x6a, 0x74, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x66, 0x65, 0x6c, 0x69, 0x78, 0x2e,
	0x67, 0x6f, 0x49, 0x53, 0x43, 0x44, 0x48, 0x43, 0x50, 0x2e, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x67,
	0x73, 0x1a, 0x37, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x2e, 0x66, 0x65, 0x6c, 0x69, 0x78, 0x2e, 0x67, 0x6f, 0x49, 0x53, 0x43, 0x44, 0x48, 0x43,
	0x50, 0x2e, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x03,
	0x47, 0x65, 0x74, 0x12, 0x30, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x2e, 0x66, 0x65, 0x6c, 0x69, 0x78, 0x2e, 0x67, 0x6f, 0x49, 0x53, 0x43, 0x44,
	0x48, 0x43, 0x50, 0x2e, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x64, 0x49, 0x64, 0x1a, 0x2e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x66, 0x65, 0x6c, 0x69, 0x78, 0x2e, 0x67, 0x6f, 0x49, 0x53,
	0x43, 0x44, 0x48, 0x43, 0x50, 0x2e, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x64, 0x22, 0x00, 0x12, 0x6e, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x30, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x2e, 0x66, 0x65, 0x6c, 0x69, 0x78, 0x2e, 0x67, 0x6f, 0x49, 0x53, 0x43, 0x44, 0x48, 0x43,
	0x50, 0x2e, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x64, 0x49, 0x64, 0x1a, 0x30, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x2e, 0x66, 0x65, 0x6c, 0x69, 0x78, 0x2e, 0x67, 0x6f, 0x49, 0x53, 0x43, 0x44,
	0x48, 0x43, 0x50, 0x2e, 0x44, 0x48, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x64, 0x49, 0x64, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6a, 0x6e, 0x74, 0x66, 0x78, 0x2f, 0x67, 0x6f,
	0x2d, 0x69, 0x73, 0x63, 0x2d, 0x64, 0x68, 0x63, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dhclient_proto_rawDescOnce sync.Once
	file_dhclient_proto_rawDescData = file_dhclient_proto_rawDesc
)

func file_dhclient_proto_rawDescGZIP() []byte {
	file_dhclient_proto_rawDescOnce.Do(func() {
		file_dhclient_proto_rawDescData = protoimpl.X.CompressGZIP(file_dhclient_proto_rawDescData)
	})
	return file_dhclient_proto_rawDescData
}

var file_dhclient_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dhclient_proto_goTypes = []interface{}{
	(*DHClient)(nil),                 // 0: com.pojtinger.felicitas.goISCDHCP.DHClient
	(*DHClientManaged)(nil),          // 1: com.pojtinger.felicitas.goISCDHCP.DHClientManaged
	(*DHClientManagerListArgs)(nil),  // 2: com.pojtinger.felicitas.goISCDHCP.DHClientManagerListArgs
	(*DHClientManagedId)(nil),        // 3: com.pojtinger.felicitas.goISCDHCP.DHClientManagedId
	(*DHClientManagerListReply)(nil), // 4: com.pojtinger.felicitas.goISCDHCP.DHClientManagerListReply
}
var file_dhclient_proto_depIdxs = []int32{
	1, // 0: com.pojtinger.felicitas.goISCDHCP.DHClientManagerListReply.DHClientsManaged:type_name -> com.pojtinger.felicitas.goISCDHCP.DHClientManaged
	0, // 1: com.pojtinger.felicitas.goISCDHCP.DHClientManager.Create:input_type -> com.pojtinger.felicitas.goISCDHCP.DHClient
	2, // 2: com.pojtinger.felicitas.goISCDHCP.DHClientManager.List:input_type -> com.pojtinger.felicitas.goISCDHCP.DHClientManagerListArgs
	3, // 3: com.pojtinger.felicitas.goISCDHCP.DHClientManager.Get:input_type -> com.pojtinger.felicitas.goISCDHCP.DHClientManagedId
	3, // 4: com.pojtinger.felicitas.goISCDHCP.DHClientManager.Delete:input_type -> com.pojtinger.felicitas.goISCDHCP.DHClientManagedId
	3, // 5: com.pojtinger.felicitas.goISCDHCP.DHClientManager.Create:output_type -> com.pojtinger.felicitas.goISCDHCP.DHClientManagedId
	4, // 6: com.pojtinger.felicitas.goISCDHCP.DHClientManager.List:output_type -> com.pojtinger.felicitas.goISCDHCP.DHClientManagerListReply
	1, // 7: com.pojtinger.felicitas.goISCDHCP.DHClientManager.Get:output_type -> com.pojtinger.felicitas.goISCDHCP.DHClientManaged
	3, // 8: com.pojtinger.felicitas.goISCDHCP.DHClientManager.Delete:output_type -> com.pojtinger.felicitas.goISCDHCP.DHClientManagedId
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dhclient_proto_init() }
func file_dhclient_proto_init() {
	if File_dhclient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dhclient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DHClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhclient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DHClientManaged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhclient_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DHClientManagerListArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhclient_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DHClientManagedId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhclient_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DHClientManagerListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dhclient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dhclient_proto_goTypes,
		DependencyIndexes: file_dhclient_proto_depIdxs,
		MessageInfos:      file_dhclient_proto_msgTypes,
	}.Build()
	File_dhclient_proto = out.File
	file_dhclient_proto_rawDesc = nil
	file_dhclient_proto_goTypes = nil
	file_dhclient_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DHClientManagerClient is the client API for DHClientManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DHClientManagerClient interface {
	Create(ctx context.Context, in *DHClient, opts ...grpc.CallOption) (*DHClientManagedId, error)
	List(ctx context.Context, in *DHClientManagerListArgs, opts ...grpc.CallOption) (*DHClientManagerListReply, error)
	Get(ctx context.Context, in *DHClientManagedId, opts ...grpc.CallOption) (*DHClientManaged, error)
	Delete(ctx context.Context, in *DHClientManagedId, opts ...grpc.CallOption) (*DHClientManagedId, error)
}

type dHClientManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewDHClientManagerClient(cc grpc.ClientConnInterface) DHClientManagerClient {
	return &dHClientManagerClient{cc}
}

func (c *dHClientManagerClient) Create(ctx context.Context, in *DHClient, opts ...grpc.CallOption) (*DHClientManagedId, error) {
	out := new(DHClientManagedId)
	err := c.cc.Invoke(ctx, "/com.pojtinger.felicitas.goISCDHCP.DHClientManager/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHClientManagerClient) List(ctx context.Context, in *DHClientManagerListArgs, opts ...grpc.CallOption) (*DHClientManagerListReply, error) {
	out := new(DHClientManagerListReply)
	err := c.cc.Invoke(ctx, "/com.pojtinger.felicitas.goISCDHCP.DHClientManager/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHClientManagerClient) Get(ctx context.Context, in *DHClientManagedId, opts ...grpc.CallOption) (*DHClientManaged, error) {
	out := new(DHClientManaged)
	err := c.cc.Invoke(ctx, "/com.pojtinger.felicitas.goISCDHCP.DHClientManager/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHClientManagerClient) Delete(ctx context.Context, in *DHClientManagedId, opts ...grpc.CallOption) (*DHClientManagedId, error) {
	out := new(DHClientManagedId)
	err := c.cc.Invoke(ctx, "/com.pojtinger.felicitas.goISCDHCP.DHClientManager/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DHClientManagerServer is the server API for DHClientManager service.
type DHClientManagerServer interface {
	Create(context.Context, *DHClient) (*DHClientManagedId, error)
	List(context.Context, *DHClientManagerListArgs) (*DHClientManagerListReply, error)
	Get(context.Context, *DHClientManagedId) (*DHClientManaged, error)
	Delete(context.Context, *DHClientManagedId) (*DHClientManagedId, error)
}

// UnimplementedDHClientManagerServer can be embedded to have forward compatible implementations.
type UnimplementedDHClientManagerServer struct {
}

func (*UnimplementedDHClientManagerServer) Create(context.Context, *DHClient) (*DHClientManagedId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedDHClientManagerServer) List(context.Context, *DHClientManagerListArgs) (*DHClientManagerListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedDHClientManagerServer) Get(context.Context, *DHClientManagedId) (*DHClientManaged, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedDHClientManagerServer) Delete(context.Context, *DHClientManagedId) (*DHClientManagedId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterDHClientManagerServer(s *grpc.Server, srv DHClientManagerServer) {
	s.RegisterService(&_DHClientManager_serviceDesc, srv)
}

func _DHClientManager_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHClient)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHClientManagerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.pojtinger.felicitas.goISCDHCP.DHClientManager/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHClientManagerServer).Create(ctx, req.(*DHClient))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHClientManager_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHClientManagerListArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHClientManagerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.pojtinger.felicitas.goISCDHCP.DHClientManager/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHClientManagerServer).List(ctx, req.(*DHClientManagerListArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHClientManager_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHClientManagedId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHClientManagerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.pojtinger.felicitas.goISCDHCP.DHClientManager/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHClientManagerServer).Get(ctx, req.(*DHClientManagedId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHClientManager_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHClientManagedId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHClientManagerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.pojtinger.felicitas.goISCDHCP.DHClientManager/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHClientManagerServer).Delete(ctx, req.(*DHClientManagedId))
	}
	return interceptor(ctx, in, info, handler)
}

var _DHClientManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.pojtinger.felicitas.goISCDHCP.DHClientManager",
	HandlerType: (*DHClientManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DHClientManager_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DHClientManager_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DHClientManager_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DHClientManager_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dhclient.proto",
}
